# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "ansi-escapes-2.0.0" = {
      name = "ansi-escapes";
      packageName = "ansi-escapes";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-escapes/-/ansi-escapes-2.0.0.tgz";
        sha1 = "5bae52be424878dd9783e8910e3fc2922e83c81b";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-regex-3.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-3.0.0.tgz";
        sha1 = "ed0317c322064f79466c02966bddb605ab37d998";
      };
    };
    "ansi-regex-4.1.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-4.1.0.tgz";
        sha512 = "1apePfXM1UOSqw0o9IiFAovVz9M5S1Dg+4TrDwfMewQ6p/rmMueb7tWZjQ1rx4Loy1ArBggoqGpfqqdI4rondg==";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "app-path-2.2.0" = {
      name = "app-path";
      packageName = "app-path";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/app-path/-/app-path-2.2.0.tgz";
        sha1 = "2af5c2b544a40e15fc1ac55548314397460845d0";
      };
    };
    "base64-js-1.2.0" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.2.0.tgz";
        sha1 = "a39992d723584811982be5e290bb6a53d86700f1";
      };
    };
    "base64-js-1.3.0" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.3.0.tgz";
        sha512 = "ccav/yGvoa80BQDljCxsmmQ3Xvx60/UpBIij5QN21W3wBi/hhIC9OoO+KLpu9IJTS9j4DRVJ3aDDF9cMSoa2lw==";
      };
    };
    "camelcase-5.3.0" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-5.3.0.tgz";
        sha512 = "Y05ICatFYPAfykDIB7VdwSJ0LUl1yq/BwO2OpyGGLjiRe1fgzTwVypPiWnzkGFOVFHXrCXUNBl86bpjBhZWSJg==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "cli-cursor-2.1.0" = {
      name = "cli-cursor";
      packageName = "cli-cursor";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-cursor/-/cli-cursor-2.1.0.tgz";
        sha1 = "b35dac376479facc3e94747d41d0d0f5238ffcb5";
      };
    };
    "cli-spinners-2.0.0" = {
      name = "cli-spinners";
      packageName = "cli-spinners";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-spinners/-/cli-spinners-2.0.0.tgz";
        sha512 = "yiEBmhaKPPeBj7wWm4GEdtPZK940p9pl3EANIrnJ3JnvWyrPjcFcsEq6qRUuQ7fzB0+Y82ld3p6B34xo95foWw==";
      };
    };
    "cliui-4.1.0" = {
      name = "cliui";
      packageName = "cliui";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cliui/-/cliui-4.1.0.tgz";
        sha512 = "4FG+RSG9DL7uEwRUZXZn3SS34DiDPfzP0VOiEwtUWlE+AR2EIg+hSyvrIgUUfhdgR/UkAeW2QHgeP+hWrXs7jQ==";
      };
    };
    "clone-1.0.4" = {
      name = "clone";
      packageName = "clone";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone/-/clone-1.0.4.tgz";
        sha1 = "da309cc263df15994c688ca902179ca3c7cd7c7e";
      };
    };
    "code-point-at-1.1.0" = {
      name = "code-point-at";
      packageName = "code-point-at";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/code-point-at/-/code-point-at-1.1.0.tgz";
        sha1 = "0d070b4d043a5bea33a2f1a40e2edb3d9a4ccf77";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "cross-spawn-6.0.5" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "6.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-6.0.5.tgz";
        sha512 = "eTVLrBSt7fjbDygz805pMnstIs2VTBNkRm0qxZd+M7A5XDdxVRWO5MxGBXZhjY4cqLYLdtrGqRf8mBPmzwSpWQ==";
      };
    };
    "cross-spawn-async-2.2.5" = {
      name = "cross-spawn-async";
      packageName = "cross-spawn-async";
      version = "2.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn-async/-/cross-spawn-async-2.2.5.tgz";
        sha1 = "845ff0c0834a3ded9d160daca6d390906bb288cc";
      };
    };
    "decamelize-1.2.0" = {
      name = "decamelize";
      packageName = "decamelize";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz";
        sha1 = "f6534d15148269b20352e7bee26f501f9a191290";
      };
    };
    "defaults-1.0.3" = {
      name = "defaults";
      packageName = "defaults";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/defaults/-/defaults-1.0.3.tgz";
        sha1 = "c656051e9817d9ff08ed881477f3fe4019f3ef7d";
      };
    };
    "end-of-stream-1.4.1" = {
      name = "end-of-stream";
      packageName = "end-of-stream";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.1.tgz";
        sha512 = "1MkrZNvWTKCaigbn+W15elq2BB/L22nqrSY5DKlo3X6+vclJm8Bb5djXJBmEX6fS3+zCh/F4VBK5Z2KxJt4s2Q==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "execa-0.4.0" = {
      name = "execa";
      packageName = "execa";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/execa/-/execa-0.4.0.tgz";
        sha1 = "4eb6467a36a095fabb2970ff9d5e3fb7bce6ebc3";
      };
    };
    "execa-1.0.0" = {
      name = "execa";
      packageName = "execa";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/execa/-/execa-1.0.0.tgz";
        sha512 = "adbxcyWV46qiHyvSp50TKt05tB4tK3HcmF7/nxfAdhnox83seTDbwnaqKO4sXRy7roHAIFqJP/Rw/AuEbX61LA==";
      };
    };
    "find-up-3.0.0" = {
      name = "find-up";
      packageName = "find-up";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-3.0.0.tgz";
        sha512 = "1yD6RmLI1XBfxugvORwlck6f75tYL+iR0jqwsOrOxMZyGYqUuDhJ0l4AXdO1iX/FTs9cBAMEk1gWSEx1kSbylg==";
      };
    };
    "get-caller-file-1.0.3" = {
      name = "get-caller-file";
      packageName = "get-caller-file";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-caller-file/-/get-caller-file-1.0.3.tgz";
        sha512 = "3t6rVToeoZfYSGd8YoLFR2DJkiQrIiUrGcjvFX2mDw3bn6k2OtwHN0TNCLbBO+w8qTvimhDkv+LSscbJY1vE6w==";
      };
    };
    "get-stream-4.1.0" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-4.1.0.tgz";
        sha512 = "GMat4EJ5161kIy2HevLlr4luNjBgvmj413KaQA7jt4V8B4RDsfpHk7WQ9GVqfYyyx8OS/L66Kox+rJRNklLK7w==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "invert-kv-2.0.0" = {
      name = "invert-kv";
      packageName = "invert-kv";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/invert-kv/-/invert-kv-2.0.0.tgz";
        sha512 = "wPVv/y/QQ/Uiirj/vh3oP+1Ww+AWehmi1g5fFWGPF6IpCBCDVrhgHRMvrLfdYcwDh3QJbGXDW4JAuzxElLSqKA==";
      };
    };
    "is-fullwidth-code-point-1.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-1.0.0.tgz";
        sha1 = "ef9e31386f031a7f0d643af82fde50c457ef00cb";
      };
    };
    "is-fullwidth-code-point-2.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-2.0.0.tgz";
        sha1 = "a3b30a5c4f199183167aaab93beefae3ddfb654f";
      };
    };
    "is-stream-1.1.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-1.1.0.tgz";
        sha1 = "12d4a3dd4e68e0b79ceb8dbc84173ae80d91ca44";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "iterm2-version-2.3.0" = {
      name = "iterm2-version";
      packageName = "iterm2-version";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/iterm2-version/-/iterm2-version-2.3.0.tgz";
        sha1 = "ae64000461e02b5f1fe5331f0b9f0ec71ce0e138";
      };
    };
    "iterm2-version-3.0.0" = {
      name = "iterm2-version";
      packageName = "iterm2-version";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/iterm2-version/-/iterm2-version-3.0.0.tgz";
        sha512 = "R2SE/AQrE4IhlyRbBp7ASIjFO+Wlpfra2Q7GMZkOjQb890MLtKyINPawJ7fr+Z7CPgHoXj2J3BNyebBIbVn8PQ==";
      };
    };
    "lcid-2.0.0" = {
      name = "lcid";
      packageName = "lcid";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lcid/-/lcid-2.0.0.tgz";
        sha512 = "avPEb8P8EGnwXKClwsNUgryVjllcRqtMYa49NTsbQagYuT1DcXnl1915oxWjoyGrXR6zH/Y0Zc96xWsPcoDKeA==";
      };
    };
    "locate-path-3.0.0" = {
      name = "locate-path";
      packageName = "locate-path";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-path/-/locate-path-3.0.0.tgz";
        sha512 = "7AO748wWnIhNqAuaty2ZWHkQHRSNfPVIsPIfwEOWO22AmaoVrWavlOcMR5nzTLNYvp36X220/maaRsrec1G65A==";
      };
    };
    "log-symbols-2.2.0" = {
      name = "log-symbols";
      packageName = "log-symbols";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/log-symbols/-/log-symbols-2.2.0.tgz";
        sha512 = "VeIAFslyIerEJLXHziedo2basKbMKtTw3vfn5IzG0XTjhAVEJyNHnL2p7vc+wBDSdQuUpNw3M2u6xb9QsAY5Eg==";
      };
    };
    "lru-cache-4.1.5" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "4.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-4.1.5.tgz";
        sha512 = "sWZlbEP2OsHNkXrMl5GYk/jKk70MBng6UU4YI/qGDYbgf6YbP4EvmqISbXCoJiRKs+1bSpFHVgQxvJ17F2li5g==";
      };
    };
    "map-age-cleaner-0.1.3" = {
      name = "map-age-cleaner";
      packageName = "map-age-cleaner";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-age-cleaner/-/map-age-cleaner-0.1.3.tgz";
        sha512 = "bJzx6nMoP6PDLPBFmg7+xRKeFZvFboMrGlxmNj9ClvX53KrmvM5bXFXEWjbz4cz1AFn+jWJ9z/DJSz7hrs0w3w==";
      };
    };
    "mem-4.3.0" = {
      name = "mem";
      packageName = "mem";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mem/-/mem-4.3.0.tgz";
        sha512 = "qX2bG48pTqYRVmDB37rn/6PT7LcR8T7oAX3bf99u1Tt1nzxYfxkgqDwUwolPlXweM0XzBOBFzSx4kfp7KP1s/w==";
      };
    };
    "mimic-fn-1.2.0" = {
      name = "mimic-fn";
      packageName = "mimic-fn";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-1.2.0.tgz";
        sha512 = "jf84uxzwiuiIVKiOLpfYk7N46TSy8ubTonmneY9vrpHNAnp0QBt2BxWV9dO3/j+BoVAb+a5G6YDPW3M5HOdMWQ==";
      };
    };
    "mimic-fn-2.1.0" = {
      name = "mimic-fn";
      packageName = "mimic-fn";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-2.1.0.tgz";
        sha512 = "OqbOk5oEQeAZ8WXWydlu9HJjz9WVdEIvamMCcXmuqUYjTknH/sqsWvhQ3vgwKFRR1HpjvNBKQ37nbJgYzGqGcg==";
      };
    };
    "nice-try-1.0.5" = {
      name = "nice-try";
      packageName = "nice-try";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/nice-try/-/nice-try-1.0.5.tgz";
        sha512 = "1nh45deeb5olNY7eX82BkPO7SSxR5SSYJiPTrTdFUVYwAl8CKMA5N9PjTYkHiRjisVcxcQ1HXdLhx2qxxJzLNQ==";
      };
    };
    "node-fetch-2.3.0" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.3.0.tgz";
        sha512 = "MOd8pV3fxENbryESLgVIeaGKrdl+uaYhCSSVkjeOb/31/njTpcis5aWfdqgNlHIrKOLRbMnfPINPOML2CIFeXA==";
      };
    };
    "npm-run-path-1.0.0" = {
      name = "npm-run-path";
      packageName = "npm-run-path";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-run-path/-/npm-run-path-1.0.0.tgz";
        sha1 = "f5c32bf595fe81ae927daec52e82f8b000ac3c8f";
      };
    };
    "npm-run-path-2.0.2" = {
      name = "npm-run-path";
      packageName = "npm-run-path";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-run-path/-/npm-run-path-2.0.2.tgz";
        sha1 = "35a9232dfa35d7067b4cb2ddf2357b1871536c5f";
      };
    };
    "number-is-nan-1.0.1" = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.1.tgz";
        sha1 = "097b602b53422a522c1afb8790318336941a011d";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "onetime-2.0.1" = {
      name = "onetime";
      packageName = "onetime";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/onetime/-/onetime-2.0.1.tgz";
        sha1 = "067428230fd67443b2794b22bba528b6867962d4";
      };
    };
    "ora-3.4.0" = {
      name = "ora";
      packageName = "ora";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ora/-/ora-3.4.0.tgz";
        sha512 = "eNwHudNbO1folBP3JsZ19v9azXWtQZjICdr3Q0TDPIaeBQ3mXLrh54wM+er0+hSp+dWKf+Z8KM58CYzEyIYxYg==";
      };
    };
    "os-locale-3.1.0" = {
      name = "os-locale";
      packageName = "os-locale";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-locale/-/os-locale-3.1.0.tgz";
        sha512 = "Z8l3R4wYWM40/52Z+S265okfFj8Kt2cC2MKY+xNi3kFs+XGI7WXu/I309QQQYbRW4ijiZ+yxs9pqEhJh0DqW3Q==";
      };
    };
    "p-defer-1.0.0" = {
      name = "p-defer";
      packageName = "p-defer";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-defer/-/p-defer-1.0.0.tgz";
        sha1 = "9f6eb182f6c9aa8cd743004a7d4f96b196b0fb0c";
      };
    };
    "p-finally-1.0.0" = {
      name = "p-finally";
      packageName = "p-finally";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-finally/-/p-finally-1.0.0.tgz";
        sha1 = "3fbcfb15b899a44123b34b6dcc18b724336a2cae";
      };
    };
    "p-is-promise-2.0.0" = {
      name = "p-is-promise";
      packageName = "p-is-promise";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-is-promise/-/p-is-promise-2.0.0.tgz";
        sha512 = "pzQPhYMCAgLAKPWD2jC3Se9fEfrD9npNos0y150EeqZll7akhEgGhTW/slB6lHku8AvYGiJ+YJ5hfHKePPgFWg==";
      };
    };
    "p-limit-2.2.0" = {
      name = "p-limit";
      packageName = "p-limit";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-limit/-/p-limit-2.2.0.tgz";
        sha512 = "pZbTJpoUsCzV48Mc9Nh51VbwO0X9cuPFE8gYwx9BTCt9SF8/b7Zljd2fVgOxhIF/HDTKgpVzs+GPhyKfjLLFRQ==";
      };
    };
    "p-locate-3.0.0" = {
      name = "p-locate";
      packageName = "p-locate";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-locate/-/p-locate-3.0.0.tgz";
        sha512 = "x+12w/To+4GFfgJhBEpiDcLozRJGegY+Ei7/z0tSLkMmxGZNybVMSfWj9aJn8Z5Fc7dBUNJOOVgPv2H7IwulSQ==";
      };
    };
    "p-try-2.2.0" = {
      name = "p-try";
      packageName = "p-try";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-try/-/p-try-2.2.0.tgz";
        sha512 = "R4nPAVTAU0B9D35/Gk3uJf/7XYbQcyohSKdvAxIRSNghFl4e71hVoGnBNQz9cWaXxO2I10KTC+3jMdvvoKw6dQ==";
      };
    };
    "path-exists-3.0.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-3.0.0.tgz";
        sha1 = "ce0ebeaa5f78cb18925ea7d810d7b59b010fd515";
      };
    };
    "path-key-1.0.0" = {
      name = "path-key";
      packageName = "path-key";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-1.0.0.tgz";
        sha1 = "5d53d578019646c0d68800db4e146e6bdc2ac7af";
      };
    };
    "path-key-2.0.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-2.0.1.tgz";
        sha1 = "411cadb574c5a140d3a4b1910d40d80cc9f40b40";
      };
    };
    "plist-2.1.0" = {
      name = "plist";
      packageName = "plist";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/plist/-/plist-2.1.0.tgz";
        sha1 = "57ccdb7a0821df21831217a3cad54e3e146a1025";
      };
    };
    "plist-3.0.1" = {
      name = "plist";
      packageName = "plist";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/plist/-/plist-3.0.1.tgz";
        sha512 = "GpgvHHocGRyQm74b6FWEZZVRroHKE1I0/BTjAmySaohK+cUn+hZpbqXkc3KWgW3gQYkqcQej35FohcT0FRlkRQ==";
      };
    };
    "pseudomap-1.0.2" = {
      name = "pseudomap";
      packageName = "pseudomap";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pseudomap/-/pseudomap-1.0.2.tgz";
        sha1 = "f052a28da70e618917ef0a8ac34c1ae5a68286b3";
      };
    };
    "pump-3.0.0" = {
      name = "pump";
      packageName = "pump";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pump/-/pump-3.0.0.tgz";
        sha512 = "LwZy+p3SFs1Pytd/jYct4wpv49HiYCqd9Rlc5ZVdk0V+8Yzv6jR5Blk3TRmPL1ft69TxP0IMZGJ+WPFU2BFhww==";
      };
    };
    "require-directory-2.1.1" = {
      name = "require-directory";
      packageName = "require-directory";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz";
        sha1 = "8c64ad5fd30dab1c976e2344ffe7f792a6a6df42";
      };
    };
    "require-main-filename-1.0.1" = {
      name = "require-main-filename";
      packageName = "require-main-filename";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-main-filename/-/require-main-filename-1.0.1.tgz";
        sha1 = "97f717b69d48784f5f526a6c5aa8ffdda055a4d1";
      };
    };
    "restore-cursor-2.0.0" = {
      name = "restore-cursor";
      packageName = "restore-cursor";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/restore-cursor/-/restore-cursor-2.0.0.tgz";
        sha1 = "9f7ee287f82fd326d4fd162923d62129eee0dfaf";
      };
    };
    "semver-5.7.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.7.0.tgz";
        sha512 = "Ya52jSX2u7QKghxeoFGpLwCtGlt7j0oY9DYb5apt9nPlJ42ID+ulTXESnt/qAQcoSERyZ5sl3LDIOw0nAn/5DA==";
      };
    };
    "set-blocking-2.0.0" = {
      name = "set-blocking";
      packageName = "set-blocking";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-blocking/-/set-blocking-2.0.0.tgz";
        sha1 = "045f9782d011ae9a6803ddd382b24392b3d890f7";
      };
    };
    "shebang-command-1.2.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-1.2.0.tgz";
        sha1 = "44aac65b695b03398968c39f363fee5deafdf1ea";
      };
    };
    "shebang-regex-1.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-1.0.0.tgz";
        sha1 = "da42f49740c0b42db2ca9728571cb190c98efea3";
      };
    };
    "signal-exit-3.0.2" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.2.tgz";
        sha1 = "b5fdc08f1287ea1178628e415e25132b73646c6d";
      };
    };
    "string-width-1.0.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-1.0.2.tgz";
        sha1 = "118bdf5b8cdc51a2a7e70d211e07e2b0b9b107d3";
      };
    };
    "string-width-2.1.1" = {
      name = "string-width";
      packageName = "string-width";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-2.1.1.tgz";
        sha512 = "nOqH59deCq9SRHlxq1Aw85Jnt4w6KvLKqWVik6oA9ZklXLNIOlqg4F2yrT1MVaTjAqvVwdfeZ7w7aCvJD7ugkw==";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "strip-ansi-4.0.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-4.0.0.tgz";
        sha1 = "a8479022eb1ac368a871389b635262c505ee368f";
      };
    };
    "strip-ansi-5.2.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-5.2.0.tgz";
        sha512 = "DuRs1gKbBqsMKIZlrffwlug8MHkcnpjs5VPmL1PAh+mA30U0DTotfDZ0d2UUsXpPmPmMMJ6W773MaA3J+lbiWA==";
      };
    };
    "strip-eof-1.0.0" = {
      name = "strip-eof";
      packageName = "strip-eof";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-eof/-/strip-eof-1.0.0.tgz";
        sha1 = "bb43ff5598a6eb05d89b59fcd129c983313606bf";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "term-img-2.1.0" = {
      name = "term-img";
      packageName = "term-img";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/term-img/-/term-img-2.1.0.tgz";
        sha512 = "j78Y+26QYTTWvtVVCmDx94idvQm6p59E+xRfQDSevIyM8dg45uUAtr/xbu13l0BeKrebPyUpgh8PM3noXlIBkw==";
      };
    };
    "wcwidth-1.0.1" = {
      name = "wcwidth";
      packageName = "wcwidth";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/wcwidth/-/wcwidth-1.0.1.tgz";
        sha1 = "f0b0dcf915bc5ff1528afadb2c0e17b532da2fe8";
      };
    };
    "which-1.3.1" = {
      name = "which";
      packageName = "which";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.3.1.tgz";
        sha512 = "HxJdYWq1MTIQbJ3nw0cqssHoTNU267KlrDuGZ1WYlxDStUtKUhOaJmh112/TZmHxxUfuJqPXSOm7tDyas0OSIQ==";
      };
    };
    "which-module-2.0.0" = {
      name = "which-module";
      packageName = "which-module";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-module/-/which-module-2.0.0.tgz";
        sha1 = "d9ef07dce77b9902b8a3a8fa4b31c3e3f7e6e87a";
      };
    };
    "wrap-ansi-2.1.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-2.1.0.tgz";
        sha1 = "d8fc3d284dd05794fe84973caecdd1cf824fdd85";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "xmlbuilder-8.2.2" = {
      name = "xmlbuilder";
      packageName = "xmlbuilder";
      version = "8.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-8.2.2.tgz";
        sha1 = "69248673410b4ba42e1a6136551d2922335aa773";
      };
    };
    "xmlbuilder-9.0.7" = {
      name = "xmlbuilder";
      packageName = "xmlbuilder";
      version = "9.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-9.0.7.tgz";
        sha1 = "132ee63d2ec5565c557e20f4c22df9aca686b10d";
      };
    };
    "xmldom-0.1.27" = {
      name = "xmldom";
      packageName = "xmldom";
      version = "0.1.27";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmldom/-/xmldom-0.1.27.tgz";
        sha1 = "d501f97b3bdb403af8ef9ecc20573187aadac0e9";
      };
    };
    "y18n-4.0.0" = {
      name = "y18n";
      packageName = "y18n";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/y18n/-/y18n-4.0.0.tgz";
        sha512 = "r9S/ZyXu/Xu9q1tYlpsLIsa3EeLXXk0VwlxqTcFRfg9EhMW+17kbt9G0NrgCmhGb5vT2hyhJZLfDGx+7+5Uj/w==";
      };
    };
    "yallist-2.1.2" = {
      name = "yallist";
      packageName = "yallist";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-2.1.2.tgz";
        sha1 = "1c11f9218f076089a47dd512f93c6699a6a81d52";
      };
    };
    "yargs-12.0.5" = {
      name = "yargs";
      packageName = "yargs";
      version = "12.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-12.0.5.tgz";
        sha512 = "Lhz8TLaYnxq/2ObqHDql8dX8CJi97oHxrjUcYtzKbbykPtVW9WB+poxI+NM2UIzsMgNCZTIf0AQwsjK5yMAqZw==";
      };
    };
    "yargs-parser-11.1.1" = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "11.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-11.1.1.tgz";
        sha512 = "C6kB/WJDiaxONLJQnF8ccx9SEeoTTLek8RVbaOIsrAUS8VrBEXfmeSnCZxygc+XC2sNMBIwOOnfcxiynjHsVSQ==";
      };
    };
  };
in
{
  twitch-chatlog = nodeEnv.buildNodePackage {
    name = "twitch-chatlog";
    packageName = "twitch-chatlog";
    version = "6.1.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/twitch-chatlog/-/twitch-chatlog-6.1.0.tgz";
      sha512 = "71f70QjnL1op8MCPmuBPEVPmJXYXvb+wIWDzJfDc0AC/igtYgufechl6snrnfsi1ZdZiJcPGbqCEZZbSQwbyRA==";
    };
    dependencies = [
      sources."ansi-escapes-2.0.0"
      sources."ansi-regex-4.1.0"
      sources."ansi-styles-3.2.1"
      sources."app-path-2.2.0"
      sources."base64-js-1.3.0"
      sources."camelcase-5.3.0"
      sources."chalk-2.4.2"
      sources."cli-cursor-2.1.0"
      sources."cli-spinners-2.0.0"
      (sources."cliui-4.1.0" // {
        dependencies = [
          sources."ansi-regex-3.0.0"
          sources."strip-ansi-4.0.0"
        ];
      })
      sources."clone-1.0.4"
      sources."code-point-at-1.1.0"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      (sources."cross-spawn-6.0.5" // {
        dependencies = [
          sources."path-key-2.0.1"
        ];
      })
      sources."cross-spawn-async-2.2.5"
      sources."decamelize-1.2.0"
      sources."defaults-1.0.3"
      sources."end-of-stream-1.4.1"
      sources."escape-string-regexp-1.0.5"
      sources."execa-0.4.0"
      sources."find-up-3.0.0"
      sources."get-caller-file-1.0.3"
      sources."get-stream-4.1.0"
      sources."has-flag-3.0.0"
      sources."invert-kv-2.0.0"
      sources."is-fullwidth-code-point-1.0.0"
      sources."is-stream-1.1.0"
      sources."isexe-2.0.0"
      sources."iterm2-version-3.0.0"
      sources."lcid-2.0.0"
      sources."locate-path-3.0.0"
      sources."log-symbols-2.2.0"
      sources."lru-cache-4.1.5"
      sources."map-age-cleaner-0.1.3"
      (sources."mem-4.3.0" // {
        dependencies = [
          sources."mimic-fn-2.1.0"
        ];
      })
      sources."mimic-fn-1.2.0"
      sources."nice-try-1.0.5"
      sources."node-fetch-2.3.0"
      sources."npm-run-path-1.0.0"
      sources."number-is-nan-1.0.1"
      sources."object-assign-4.1.1"
      sources."once-1.4.0"
      sources."onetime-2.0.1"
      sources."ora-3.4.0"
      (sources."os-locale-3.1.0" // {
        dependencies = [
          sources."execa-1.0.0"
          sources."npm-run-path-2.0.2"
          sources."path-key-2.0.1"
        ];
      })
      sources."p-defer-1.0.0"
      sources."p-finally-1.0.0"
      sources."p-is-promise-2.0.0"
      sources."p-limit-2.2.0"
      sources."p-locate-3.0.0"
      sources."p-try-2.2.0"
      sources."path-exists-3.0.0"
      sources."path-key-1.0.0"
      sources."plist-3.0.1"
      sources."pseudomap-1.0.2"
      sources."pump-3.0.0"
      sources."require-directory-2.1.1"
      sources."require-main-filename-1.0.1"
      sources."restore-cursor-2.0.0"
      sources."semver-5.7.0"
      sources."set-blocking-2.0.0"
      sources."shebang-command-1.2.0"
      sources."shebang-regex-1.0.0"
      sources."signal-exit-3.0.2"
      (sources."string-width-2.1.1" // {
        dependencies = [
          sources."ansi-regex-3.0.0"
          sources."is-fullwidth-code-point-2.0.0"
          sources."strip-ansi-4.0.0"
        ];
      })
      sources."strip-ansi-5.2.0"
      sources."strip-eof-1.0.0"
      sources."supports-color-5.5.0"
      (sources."term-img-2.1.0" // {
        dependencies = [
          sources."base64-js-1.2.0"
          sources."iterm2-version-2.3.0"
          sources."plist-2.1.0"
          sources."xmlbuilder-8.2.2"
        ];
      })
      sources."wcwidth-1.0.1"
      sources."which-1.3.1"
      sources."which-module-2.0.0"
      (sources."wrap-ansi-2.1.0" // {
        dependencies = [
          sources."ansi-regex-2.1.1"
          sources."string-width-1.0.2"
          sources."strip-ansi-3.0.1"
        ];
      })
      sources."wrappy-1.0.2"
      sources."xmlbuilder-9.0.7"
      sources."xmldom-0.1.27"
      sources."y18n-4.0.0"
      sources."yallist-2.1.2"
      sources."yargs-12.0.5"
      sources."yargs-parser-11.1.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Fetch the chat log to a Twitch VOD.";
      homepage = https://github.com/freaktechnik/twitch-chatlog;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
}